In [1]:
# Machine Learning Data Exploration
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/daan/Desktop/Nova IMS/Machine Learning/Project/project_data/train_data.csv', sep= ",")
df

/var/folders/cb/8gnf1rrd7914vbmqtgrt2mmm0000gn/T/ipykernel_4864/1559504511.py:1: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/daan/Desktop/Nova IMS/Machine Learning/Project/project_data/train_data.csv', sep= ",")

,Accident Date,Age at Injury,Alternative Dispute Resolution,Assembly Date,Attorney/Representative,Average Weekly Wage,Birth Year,C-2 Date,C-3 Date,Carrier Name,...,WCIO Cause of Injury Code,WCIO Cause of Injury Description,WCIO Nature of Injury Code,WCIO Nature of Injury Description,WCIO Part Of Body Code,WCIO Part Of Body Description,Zip Code,Agreement Reached,WCB Decision,Number of Dependents
0,2019-12-30,31.0,N,2020-01-01,N,0.00,1988.0,2019-12-31,NaN,NEW HAMPSHIRE INSURANCE CO,...,27.0,FROM LIQUID OR GREASE SPILLS,10.0,CONTUSION,62.0,BUTTOCKS,13662,0.0,Not Work Related,1.0
1,2019-08-30,46.0,N,2020-01-01,Y,1745.93,1973.0,2020-01-01,2020-01-14,ZURICH AMERICAN INSURANCE CO,...,97.0,REPETITIVE MOTION,49.0,SPRAIN OR TEAR,38.0,SHOULDER(S),14569,1.0,Not Work Related,4.0
2,2019-12-06,40.0,N,2020-01-01,N,1434.80,1979.0,2020-01-01,NaN,INDEMNITY INSURANCE CO OF,...,79.0,OBJECT BEING LIFTED OR HANDLED,7.0,CONCUSSION,10.0,MULTIPLE HEAD INJURY,12589,0.0,Not Work Related,6.0
3,NaN,NaN,NaN,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-12-30,61.0,N,2020-01-01,N,NaN,1958.0,2019-12-31,NaN,STATE INSURANCE FUND,...,16.0,"HAND TOOL, UTENSIL; NOT POWERED",43.0,PUNCTURE,36.0,FINGER(S),12603,0.0,Not Work Related,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593466,NaN,NaN,NaN,2022-12-31,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593467,2022-12-13,72.0,N,2022-12-31,N,0.00,1950.0,2022-12-31,NaN,TECHNOLOGY INSURANCE CO. INC.,...,25.0,FROM DIFFERENT LEVEL (ELEVATION),90.0,MULTIPLE PHYSICAL INJURIES ONLY,-9.0,MULTIPLE,12779,0.0,Not Work Related,3.0
593468,NaN,NaN,NaN,2022-12-31,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593469,NaN,NaN,NaN,2022-12-31,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593470,NaN,NaN,NaN,2022-12-31,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape

(593471, 33)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 593471 entries, 0 to 593470
Data columns (total 33 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Accident Date                       570337 non-null  object
 1   Age at Injury                       574026 non-null  float64
 2   Alternative Dispute Resolution      574026 non-null  object
 3   Assembly Date                       593471 non-null  object
 4   Attorney/Representative             574026 non-null  object
 5   Average Weekly Wage                 545375 non-null  float64
 6   Birth Year                          544948 non-null  float64
 7   C-2 Date                            559466 non-null  object
 8   C-3 Date                            187245 non-null  object
 9   Carrier Name                        574026 non-null  object
 10  Carrier Type                        574026 non-null  object
 11  Claim Identifier                    593471 non-null  int64
 12  Claim Injury Type                   574026 non-null  object
 13  County of Injury                    574026 non-null  object
 14  COVID-19 Indicator                  574026 non-null  object
 15  District Name                       574026 non-null  object
 16  First Hearing Date                  150798 non-null  object
 17  Gender                              574026 non-null  object
 18  IME-4 Count                         132803 non-null  float64
 19  Industry Code                       564068 non-null  float64
 20  Industry Code Description           564068 non-null  object
 21  Medical Fee Region                  574026 non-null  object
 22  OIICS Nature of Injury Description  0 non-null       float64
 23  WCIO Cause of Injury Code           558386 non-null  float64
 24  WCIO Cause of Injury Description    558386 non-null  object
 25  WCIO Nature of Injury Code          558369 non-null  float64
 26  WCIO Nature of Injury Description   558369 non-null  object
 27  WCIO Part Of Body Code              556944 non-null  float64
 28  WCIO Part Of Body Description       556944 non-null  object
 29  Zip Code                            545389 non-null  object
 30  Agreement Reached                   574026 non-null  float64
 31  WCB Decision                        574026 non-null  object
 32  Number of Dependents                574026 non-null  float64
dtypes: float64(11), int64(1), object(21)
memory usage: 149.4+ MB

In [5]:
list(df["WCB Decision"].drop_duplicates())

['Not Work Related', nan]

In [6]:
df_2 = df[["WCB Decision", "WCIO Cause of Injury Code", "WCIO Cause of Injury Description","Accident Date"]]
df_2

,WCB Decision,WCIO Cause of Injury Code,WCIO Cause of Injury Description,Accident Date
0,Not Work Related,27.0,FROM LIQUID OR GREASE SPILLS,2019-12-30
1,Not Work Related,97.0,REPETITIVE MOTION,2019-08-30
2,Not Work Related,79.0,OBJECT BEING LIFTED OR HANDLED,2019-12-06
3,NaN,NaN,NaN,NaN
4,Not Work Related,16.0,"HAND TOOL, UTENSIL; NOT POWERED",2019-12-30
...,...,...,...,...
593466,NaN,NaN,NaN,NaN
593467,Not Work Related,25.0,FROM DIFFERENT LEVEL (ELEVATION),2022-12-13
593468,NaN,NaN,NaN,NaN
593469,NaN,NaN,NaN,NaN
593470,NaN,NaN,NaN,NaN

In [7]:
df_with_NaN = df_2[df_2["WCB Decision"] != "Not Work Related"]
df_with_NaN
df_with_NaN.drop_duplicates()

,WCB Decision,WCIO Cause of Injury Code,WCIO Cause of Injury Description,Accident Date
3,NaN,NaN,NaN,NaN

In [8]:
df_without_NaN = df_2.dropna
df_without_NaN()

,WCB Decision,WCIO Cause of Injury Code,WCIO Cause of Injury Description,Accident Date
0,Not Work Related,27.0,FROM LIQUID OR GREASE SPILLS,2019-12-30
1,Not Work Related,97.0,REPETITIVE MOTION,2019-08-30
2,Not Work Related,79.0,OBJECT BEING LIFTED OR HANDLED,2019-12-06
4,Not Work Related,16.0,"HAND TOOL, UTENSIL; NOT POWERED",2019-12-30
5,Not Work Related,31.0,"FALL, SLIP OR TRIP, NOC",2019-12-26
...,...,...,...,...
593451,Not Work Related,45.0,COLLISION OR SIDESWIPE WITH ANOTHER VEHICLE,2022-12-14
593455,Not Work Related,74.0,"FELLOW WORKER, PATIENT OR OTHER PERSON",2022-12-15
593456,Not Work Related,98.0,"CUMULATIVE, NOC",2022-12-13
593457,Not Work Related,59.0,USING TOOL OR MACHINERY,2022-12-14
593467,Not Work Related,25.0,FROM DIFFERENT LEVEL (ELEVATION),2022-12-13